version: 2.1

executors:
  default:
    working_directory: ~/mattermost-webapp
    docker:
      - image: mattermost/mattermost-build-webapp:oct-2-2018

jobs:
  setup:
    executor:
      name: default
    steps:
      - run: |
          ls -la
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          git clone git@github.com:mattermost/mattermost-webapp.git
          cd mattermost-webapp
          git checkout $CIRCLE_BRANCH || git checkout master
          export WEBAPP_GIT_COMMIT=$(git rev-parse HEAD)
          echo "$WEBAPP_GIT_COMMIT"
          curl -f -o ./dist.tar.gz https://releases.mattermost.com/mattermost-webapp/commit/${WEBAPP_GIT_COMMIT}/mattermost-webapp.tar.gz && mkdir ./dist && tar -xvf ./dist.tar.gz -C ./dist --strip-components=1 || make node_modules test build

workflows:
  version: 2
  untagged-build:
    jobs:
      - setup
